In [2]:
#pip install numpy

In [4]:
import numpy as np

In [7]:
a=np.array([4,5,6])
a

array([4, 5, 6])

In [11]:
b=np.array([[2,3,4],[9,5,6]])
b

array([[2, 3, 4],
       [9, 5, 6]])

In [14]:
a.ndim#dimension

1

In [16]:
b.shape

(2, 3)

In [18]:
b.dtype

dtype('int32')

In [20]:
a.itemsize

4

In [23]:
a.nbytes

12

In [25]:
c=np.array([[2,3,4,6,7,5],[4,5,6,7,8,9]])
c

array([[2, 3, 4, 6, 7, 5],
       [4, 5, 6, 7, 8, 9]])

In [28]:
c[1,2]

6

In [30]:
c[0,:]

array([2, 3, 4, 6, 7, 5])

In [31]:
c[:,2]

array([4, 6])

In [34]:
c=np.identity(4)
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
c+2

array([[3., 2., 2., 2.],
       [2., 3., 2., 2.],
       [2., 2., 3., 2.],
       [2., 2., 2., 3.]])

In [38]:
c-2

array([[-1., -2., -2., -2.],
       [-2., -1., -2., -2.],
       [-2., -2., -1., -2.],
       [-2., -2., -2., -1.]])